import { Roboto } from 'next/font/google'

import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const fonts = Roboto({ subsets: ['latin'], weight: ['100', '300', '400', '700', '900'] })

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={fonts.className}>
      <body className='flex flex-col overflow-hidden bg-primary text-tertiary'>
        <header className='flex justify-between md:px-40 py-5 items-center h-[70px] bg-secondary drop-shadow-sm'>
          <span className='text-xl font-light'>LOGO</span>
          <h1 className='text-2xl font-light'>Santiago Mendoza</h1>
        </header>
        <main className='h-[calc(100vh-110px)] md:mx-40 py-5'>
          {children}
        </main>
        <footer className='flex justify-center md:px-40 py-5 items-center h-[40px] bg-secondary drop-shadow-lg'>
          <span className='text-sm font-light'>Powered by Matias Inchauspe</span>
        </footer>
      </body>
    </html>
  )
}
